### ISSUE TITLE
The app crashed

### ISSUE THREAD

**Issue by nilscox** [Bopzor/movies-list#7]
Hello,

the app crashed with a message in the console:
```
Error during service worker registration: DOMException: "The operation is insecure." registerServiceWorker.js:80:6
Invariant Violation: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
```

I dunno how to reproduce exactly, the page just disappeared... good luck with that x)

**Comment by Bopzor** [comment]
Hello,

I find something that could be the cause (got a setState in render method ooops).
Fix in 124012f commit.

Soon in prod.

Thank's for reporting !

**Comment by nilscox** [comment]
Any updates on this?

**Comment by nilscox** [comment]
Is a release date already set?

**Comment by nilscox** [comment]
Hi, is this repo still maintained? Any upadate on the initial issue?
Thank you

**Comment by Bopzor** [comment]
Hey.
Sorry, I put pause on this project for now but I will soon come back to it.
Thank you for asking news !!

**Comment by Bopzor** [comment]
Hello !
Do you remember which browser you were using when this happened?
Anyways, it possibly happened because of HTTP over HTTPS.
Not sure. I didn't manage to reproduce it yet.

**Comment by nilscox** [comment]
This may have been resolved with the new releases. Let's close it for now and reopen it with more information about how to reproduce if it actually rehappens.
