### ISSUE TITLE
Search results fails

### ISSUE THREAD

**Issue by nilscox** [Bopzor/movies-list#8]
Hello,

Steps to reproduce:
- type `nigtnmare` in the search input
- wait for the debounce to timeout and load the results
- type `bef`

Expected behavior: the search results displays "the nightmare before christmast"
Actual behavior: the search results closes

Possible solution: when the search fails, retry without the last word

**Comment by Bopzor** [comment]
Hello,

Thank's for reporting.

I found that it came from the OMDB API, so I try out your solution. (768b7e8)
It will soon be on prod :)
